### ISSUE TITLE
调用spend方法的格式问题

### ISSUE THREAD

**Issue by Wangmmx** [bitbill/bitbill-multisig-contracts#1]
spend中参数需要签名的vs，rs，ss参数，具体的格式规则有example可以参考吗，vs经过sign之后默认为unit型，有unit[] 8的格式的例子吗，我本地测试一直报格式错误？

**Comment by alexeyneu** [comment]
@Wangmmx yeah they dont have a clue just. really it checks `r s v`  ofc.
